### ISSUE TITLE
Unable to unmarshal Locaton list

### ISSUE THREAD

**Issue by nikiforidi** [forestvpn/api-client-go#1]
**Describe the bug**
A json error in [ListLocations](https://github.com/forestvpn/api-client-go/blob/main/docs/GeoApi.md#listlocations):
`json: cannot unmarshal number 25.276987 into Go struct field Location.latitude of type int32
`

**To Reproduce**
Steps to reproduce the behaviour:
1. Execute [GetLocations](https://github.com/forestvpn/api-client-go/blob/main/docs/GeoApi.md#listlocations) request as in example

**Expected behaviour**
Should get an array of Location structures.

**Environment:**
 - OS: Docker
 - Version: go version go1.18.3 linux/arm64

**Additional context**
The error message actually shows the latitude value as a float number coming from an API server. Both latitude and longitude are usually float numbers. At the same time, the Location structure defines their types as `int32`: https://github.com/forestvpn/api-client-go/blob/0eb8b1cc65567f4f9d2f9a262b43d581c6dc38a5/model_location.go#L19-L26. 
Shouldn’t they be `float32` or `float64`?

**Comment by suquant** [comment]
@anatolio-deb Thanks, it's fixed.
